// Mock data for local development (USE_MOCK_DATA=true)
// Simulates SharePoint data without real Azure credentials

import type { UseCase, Incident, AuditEntry } from './mappers';

const NOW = new Date().toISOString();
const ADMIN = 'admin@demo.local';

export const MOCK_USECASES: UseCase[] = [
  {
    id: 'UC-001',
    title: 'ChatGPT Dokumentenanalyse',
    cl: 'Vertrieb',
    sys: 'Microsoft 365 Copilot',
    legacy: '',
    own: 'Vertriebsleitung',
    cap: 'Generative KI',
    kiType: ['einsatz'],
    auto: 'Assistiert',
    lc: 'Live',
    pd: 'Scale',
    rt: 'High',
    tier: '3',
    rev: 'yes',
    vs: 4,
    fs: 3,
    rs: 4,
    kpi: 'yes',
    app: 'Approved',
    or: 'Ready',
    hitl: 'yes',
    gt: [true, true, true, false],
    sb: [true, false, true, false],
    mc: [true, true, false, true, false, false, true],
    act: true,
    desc: 'Analyse von Kundenangeboten und Verträgen mit ChatGPT Enterprise. Erkennung von Risikopositionen und Preisabweichungen.',
    link: 'https://example.com/uc-001',
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: NOW,
    createdBy: ADMIN,
    updatedBy: ADMIN,
    _spId: 'sp-001',
  },
  {
    id: 'UC-002',
    title: 'KI-gestützte Bedarfsplanung',
    cl: 'SCM',
    sys: 'SAP IBP + Azure ML',
    legacy: 'SAP APO',
    own: 'Supply Chain Manager',
    cap: 'Predictive Analytics',
    kiType: ['einsatz', 'erstellung'],
    auto: 'Entscheidet',
    lc: 'Pilot',
    pd: 'Scale',
    rt: 'Medium',
    tier: '2',
    rev: 'yes',
    vs: 5,
    fs: 4,
    rs: 3,
    kpi: 'pending',
    app: 'Pending',
    or: 'Partial',
    hitl: 'yes',
    gt: [true, true, false, false],
    sb: [true, false, false, false],
    mc: [false, false, false, true, false, false, false],
    act: true,
    desc: 'Prognosemodell für Rohmaterialbedarf auf Basis historischer Verkaufsdaten, Wetter und Marktindikatoren.',
    link: '',
    createdAt: '2025-03-01T10:00:00Z',
    updatedAt: NOW,
    createdBy: ADMIN,
    updatedBy: ADMIN,
    _spId: 'sp-002',
  },
  {
    id: 'UC-003',
    title: 'Automatische E-Mail-Klassifikation',
    cl: 'IT',
    sys: 'Azure AI Services',
    legacy: '',
    own: 'IT-Leitung',
    cap: 'Klassifikation',
    kiType: ['erstellung'],
    auto: 'Automatisch',
    lc: 'Idea',
    pd: 'Start',
    rt: 'Low',
    tier: '1',
    rev: 'yes',
    vs: 3,
    fs: 5,
    rs: 1,
    kpi: 'no',
    app: 'Not required',
    or: 'Not ready',
    hitl: 'no',
    gt: [false, false, false, false],
    sb: [false, false, false, false],
    mc: [false, false, false, false, false, false, false],
    act: true,
    desc: 'Klassifikation eingehender Kundenanfragen in Kategorien (Bestellung, Reklamation, Anfrage) zur automatischen Weiterleitung.',
    link: '',
    createdAt: '2025-04-10T14:00:00Z',
    updatedAt: NOW,
    createdBy: 'editor@demo.local',
    updatedBy: 'editor@demo.local',
    _spId: 'sp-003',
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'INC-001',
    ucid: 'UC-001',
    type: 'Bias/Fairness',
    sev: 'High',
    st: 'Open',
    desc: 'ChatGPT hat in 3 Angeboten irreführende Rabattformulierungen generiert, die vom Vertrieb ungeprüft an Kunden weitergeleitet wurden.',
    act: 'Review-Prozess vor Versand einführen; Prompt-Guardrails anpassen',
    date: '2025-04-22',
    createdAt: '2025-04-22T08:30:00Z',
    updatedAt: NOW,
    createdBy: ADMIN,
    updatedBy: ADMIN,
    _spId: 'sp-inc-001',
  },
  {
    id: 'INC-002',
    ucid: 'UC-002',
    type: 'Modell-Drift',
    sev: 'Medium',
    st: 'InProgress',
    desc: 'Prognosegenauigkeit in KW 15-17 um 12% gesunken — Ursache: Lieferkettenstörung nicht im Trainings-Set repräsentiert.',
    act: 'Retraining mit aktualisierten Daten angesetzt (KW 19)',
    date: '2025-04-28',
    createdAt: '2025-04-28T11:00:00Z',
    updatedAt: NOW,
    createdBy: 'editor@demo.local',
    updatedBy: ADMIN,
    _spId: 'sp-inc-002',
  },
];

export const MOCK_AUDIT: AuditEntry[] = [
  {
    id: 'AUD-001',
    ts: '2025-04-22T08:35:00Z',
    actor: ADMIN,
    action: 'create',
    entity: 'Incident',
    entityId: 'INC-001',
    diff: {},
    comment: '',
    _spId: 'sp-aud-001',
  },
  {
    id: 'AUD-002',
    ts: '2025-04-20T14:10:00Z',
    actor: ADMIN,
    action: 'approve',
    entity: 'UseCase',
    entityId: 'UC-001',
    diff: { app: { before: 'Pending', after: 'Approved' } },
    comment: 'Risk Assessment + Gate A abgeschlossen',
    _spId: 'sp-aud-002',
  },
  {
    id: 'AUD-003',
    ts: '2025-03-01T10:05:00Z',
    actor: ADMIN,
    action: 'create',
    entity: 'UseCase',
    entityId: 'UC-002',
    diff: {},
    comment: '',
    _spId: 'sp-aud-003',
  },
];

// Mock artefakte payloads keyed by ucId
export const MOCK_ARTEFAKTE: Record<string, Record<string, Record<string, unknown>>> = {
  'UC-001': {
    ra: {
      d1: { w: 4, s: 3 }, d2: { w: 3, s: 2 }, d3: { w: 4, s: 4 },
      d4: { w: 2, s: 2 }, d5: { w: 3, s: 3 }, d6: { w: 2, s: 2 }, d7: { w: 3, s: 3 },
      eu: { eu1: true, eu2: false, eu3: false, eu4: false, eu5: false, eu6: false, eu7: false },
      mit: { m1: 'HITL-Review vor Versand', m2: '', m3: 'Audit-Logging aktiv', m4: '', m5: '', m6: '', m7: '' },
    },
    gc: {
      a: { a1: true, a2: true, a3: true, a4: true, a5: false, a6: true, a7: true, a8: false, a9: true },
      b: { b1: false, b2: false, b3: false, b4: false, b5: false, b6: false, b7: false, b8: false, b9: false, b10: false },
      c: { c1: false, c2: false, c3: false, c4: false, c5: false, c6: false, c7: false, c8: false, c9: false, c10: false },
    },
    bc: {},
    dsfa: {},
  },
};
